DROP USER IF EXISTS 'cs127'@'localhost';
CREATE USER 'cs127'@'localhost' IDENTIFIED BY 'cs127';
DROP DATABASE IF EXISTS 6TenRRS;
CREATE DATABASE 6TenRRS;
GRANT SUPER ON *.* TO 'cs127'@'localhost';
GRANT ALL PRIVILEGES ON 6TenRRS.* TO 'cs127'@'localhost' WITH GRANT OPTION;
USE 6TenRRS;


CREATE TABLE USER (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
)ENGINE=InnoDB;


CREATE TABLE CUSTOMER (
	CustomerID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(255) NOT NULL ,
	Address VARCHAR(255) NOT NULL,
	ContactNum VARCHAR(11) NOT NULL,
	Birthday Date NOT NULL,
	Age INT NOT NULL
)ENGINE=InnoDB;


CREATE TABLE BRANCH (
	BranchID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	BranchLocation VARCHAR(255) NOT NULL,
	BranchManager VARCHAR(255) NOT NULL
)ENGINE=InnoDB;


CREATE TABLE PRODUCT (
	ProdID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ProdName VARCHAR(255) NOT NULL,
	Price INT NOT NULL

)ENGINE=InnoDB;

CREATE TABLE STOCK (
	StockID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Product_id INT NOT NULL,
	Branch_id INT NOT NULL,
	Quantity INT NOT NULL,
	CONSTRAINT product_id_fk FOREIGN KEY (Product_id)
	REFERENCES PRODUCT(ProdID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT branch_id_fk FOREIGN KEY (Branch_id)
	REFERENCES BRANCH(BranchID) 
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE PROMO (
	PromoID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	StarsEarnable INT NOT NULL,
	StarsNeeded INT NOT NULL,
	ExprDate Date NOT NULL,
	ProductID INT NOT NULL,
	CONSTRAINT prod_id_fk FOREIGN KEY (ProductID)
	REFERENCES PRODUCT(ProdID)
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE PROMOSTAR (
	PromoStarID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Starsval INT NOT NULL,
	DateUsed datetime DEFAULT NULL,
	DateEarned datetime NOT NULL,
	ExprDate Date NOT NULL,
	CustomerId INT NOT NULL,
	PromoId INT NOT NULL,
	CONSTRAINT promo_id_fk FOREIGN KEY (PromoId)
	REFERENCES PROMO(PromoID) ON DELETE CASCADE,
	CONSTRAINT customer_id_fk FOREIGN KEY (CustomerId)
	REFERENCES CUSTOMER(CustomerID)
	ON DELETE CASCADE

)ENGINE=InnoDB;



CREATE TABLE REWARD (
	RewardID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Points INT NOT NULL,
	DateUsed datetime DEFAULT NULL,
	DateEarned datetime NOT NULL,
	CustomerId INT NOT NULL,
	CONSTRAINT rewards_customer_id_fk FOREIGN KEY (CustomerId)
	REFERENCES CUSTOMER(CustomerID)
	ON DELETE CASCADE
)ENGINE=InnoDB;


CREATE TABLE TRANSACTION (
	TransID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Payment_amt INT NOT NULL,
	Payment_type enum("PESO","POINTS") NOT NULL,
	TransDesc VARCHAR(255) NOT NULL,
	DateCreated datetime NOT NULL,
	DateUpdated datetime NOT NULL,
	CustomerId INT NOT NULL,
	BranchId INT NOT NULL,
	CONSTRAINT branchid_fk FOREIGN KEY (BranchId)
	REFERENCES BRANCH(BranchID) ON DELETE CASCADE,
	CONSTRAINT customerid_fk FOREIGN KEY (CustomerId)
	REFERENCES CUSTOMER(CustomerID)
	ON DELETE CASCADE

)ENGINE=InnoDB;

INSERT INTO USER VALUES (DEFAULT,'admin','admin');